# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'errorpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_For(object):
    def setupUi(self, For):
        For.setObjectName("For")
        For.resize(354, 96)
        self.pushButton = QtWidgets.QPushButton(For)
        self.pushButton.setGeometry(QtCore.QRect(120, 50, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(For)
        self.label.setGeometry(QtCore.QRect(100, 20, 161, 20))
        self.label.setObjectName("label")

        self.retranslateUi(For)
        QtCore.QMetaObject.connectSlotsByName(For)

    def retranslateUi(self, For):
        _translate = QtCore.QCoreApplication.translate
        For.setWindowTitle(_translate("For", "Form"))
        self.pushButton.setText(_translate("For", "Continue"))
        self.label.setText(_translate("For", "Passwords do not match"))
