# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'infopage.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 224)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(170, 190, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 481, 171))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Exit"))
        self.textEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" "
                                                 "\"http://www.w3.org/TR/REC-html40/strict.dtd\">\n "
                                                 "<html><head><meta name=\"qrichtext\" content=\"1\" /><style "
                                                 "type=\"text/css\">\n "
                                                 "p, li { white-space: pre-wrap; }\n"
                                                 "</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; "
                                                 "font-size:13pt; font-weight:400; font-style:normal;\">\n "
                                                 "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; "
                                                 "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span "
                                                 "style=\" font-weight:600;\">Tested file formats:</span> .png, .pdf, "
                                                 ".json, .sol, .jpg, .mp3, .wav, .ogg, .avi, .mov, .mp4, .wmv, .doc, "
                                                 ".xls, .ppt, .odt, .ods, .odp, .rtf, .webp, .gif, .ico, .html, .csv, "
                                                 ".zip, .swift, .plist, .djvu, .ott, xlsx, .lrf, .fb2, .epub, .azw3, "
                                                 ".erf, .hdf, .nef, .vob, .rm, .8svx</p>\n "
                                                 "<p style=\"-qt-paragraph-type:empty; margin-top:0px; "
                                                 "margin-bottom:0px; margin-left:0px; margin-right:0px; "
                                                 "-qt-block-indent:0; text-indent:0px;\"><br /></p>\n "
                                                 "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; "
                                                 "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span "
                                                 "style=\" font-weight:600;\">Tested file sizes:</span> up to "
                                                 "5GB</p>\n "
                                                 "<p style=\"-qt-paragraph-type:empty; margin-top:0px; "
                                                 "margin-bottom:0px; margin-left:0px; margin-right:0px; "
                                                 "-qt-block-indent:0; text-indent:0px;\"><br /></p>\n "
                                                 "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; "
                                                 "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span "
                                                 "style=\" font-weight:600;\">Supported cloud providers:</span> Azure "
                                                 "blob storage</p>\n "
                                                 "<p style=\"-qt-paragraph-type:empty; margin-top:0px; "
                                                 "margin-bottom:0px; margin-left:0px; margin-right:0px; "
                                                 "-qt-block-indent:0; text-indent:0px;\"><br /></p>\n "
                                                 "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; "
                                                 "margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span "
                                                 "style=\" font-weight:600;\">Created by:</span> Viktor Wilczek "
                                                 "</p></body></html>"))
